server:
  port: 3000

spring:
  application:
    name: stall-map-backend
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:mysql://test-db-mysql.ns-5kijrvqd.svc:3306/觅摊?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: w6k54c6l
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:sql/init.sql
      mode: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

logging:
  level:
    com.stallmap: info

